services:
  frontend-dev:
    image: node:20-alpine
    working_dir: /workspace
    command: sh -c "npm ci && npm run start"
    ports:
      - "4200:4200"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - type: volume
        source: frontend-node_modules
        target: /workspace/node_modules
    depends_on:
      - backend

volumes:
  frontend-node_modules:
